version: '3'

services:
  galaxy-chatbot:
    build: .
    container_name: galaxy-chatbot
    restart: unless-stopped
    ports:
      - "${PORT:-8000}:${PORT:-8000}"
    environment:
      - PORT=${PORT:-8000}
      - MALLOC_ARENA_MAX=2
      - PYTHONMALLOC=malloc
      - PYTHONDONTWRITEBYTECODE=1
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - COHERE_API_KEY=${COHERE_API_KEY}
    mem_limit: 512m
    mem_reservation: 256m
    env_file:
      - .env
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M 